/*
     1 - EXCLUIR PASTAS CONTROLLER 
     2 - ADIÇÃO PASTA MODELS E CLASSES QUE SERÃO AS TABELAS
     3 - INSTALAÇÃO DE PACOTES NUGETS E Ferramenta EF Core Tools (ESSA É NO CONSOLE)
     4 - CRIAR PASTA DE CONTEXT E ARQUIVO DE CONTEXTO PARA ACESSAR BD


 
 
 
*/